language: cpp
compiler:
  - gcc

script: "rake; rake test:unit"

branches:
  only:
    - master
    - feature/travis_ci

install:
  - sudo apt-get install luajit

notifications:
  recipients:
    - iyatomi+yue.test@gmail.com
  email:
    on_success: change
    on_failure: always
