language: cpp
compiler:
  - gcc

script: "rake build:release && sudo rake install && rake test:unit"

branches:
  only:
    - master
    - feature/travis_ci

notifications:
  recipients:
    - iyatomi+yue.test@gmail.com
  email:
    on_success: change
    on_failure: always
